#!/bin/sh

for NIX_DIRENV_INIT in \
  "/run/current-system/sw/share/nix-direnv/direnvrc" \
  "$HOME/.nix-profile/share/nix-direnv/direnvrc"; do
  if [ -f "$NIX_DIRENV_INIT" ]; then
    source "$NIX_DIRENV_INIT"
    break
  fi
done

layout_uv() {
  if [[ -d ".venv" ]]; then
    VIRTUAL_ENV="$(pwd)/.venv"
  fi

  if [[ -z $VIRTUAL_ENV || ! -d $VIRTUAL_ENV ]]; then
    log_status 'No uv project exists. Executing `uv init` to create one.'
    uv init --no-readme
    rm hello.py
    uv venv
    VIRTUAL_ENV="$(pwd)/.venv"
  fi

  PATH_add "$VIRTUAL_ENV/bin"
  export UV_ACTIVE=1 # or VENV_ACTIVE=1
  export VIRTUAL_ENV
}
