# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[directory]
style = "blue"
read_only = " 󰌾"

# Language / environment specific configuration
[aws]
symbol = "  "

[buf]
symbol = " "
format = "[$symbol]($style)"

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "
format = "[$symbol]($style)"

[dart]
symbol = " "
format = "[$symbol]($style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = '[$symbol]($style)'

[elm]
symbol = " "
format = '[$symbol]($style)'

[fennel]
symbol = " "
format = '[$symbol]($style)'

[fossil_branch]
symbol = " "
format = "[$symbol]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch ]($style)"
style = "green"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "yellow"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
stashed = "≡"
deleted = ""
renamed = ""

[golang]
symbol = " "
format = '[$symbol]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "
format = '[$symbol]($style)'

[hg_branch]
symbol = " "
format = "[$symbol]($style)"

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = '[$symbol]($style)'

[julia]
symbol = " "
format = '[$symbol]($style)'

[kotlin]
symbol = " "
format = '[$symbol]($style)'

[lua]
symbol = " "
format = '[$symbol]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
format = '[$symbol]($style)'

[nix_shell]
symbol = " "
format = '[$symbol]($style)'

[nodejs]
symbol = " "
format = '[$symbol]($style)'

[ocaml]
symbol = " "
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
disabled = true

[perl]
symbol = " "
format = '[$symbol]($style)'

[php]
symbol = " "
format = '[$symbol]($style)'

[pijul_channel]
symbol = " "
format = "[$symbol]($style)"

[python]
symbol = " "
format = '[$symbol]($style)'

[rlang]
symbol = "󰟔 "
format = '[$symbol]($style)'

[ruby]
symbol = " "
format = '[$symbol]($style)'

[rust]
symbol = " "
format = '[$symbol]($style)'

[scala]
symbol = " "

[swift]
symbol = " "
format = '[$symbol]($style)'

[zig]
symbol = " "
format = '[$symbol]($style)'
